CREATE DATABASE CountryApiDb;
GO

USE CountryApiDb;
GO

CREATE TABLE Countries
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CountryCode NVARCHAR(3) NOT NULL UNIQUE,
    Name NVARCHAR(100) NOT NULL,
    Capital NVARCHAR(100) NULL,
    Region NVARCHAR(50) NULL,
    Population BIGINT NULL,
    Area DECIMAL(18,2) NULL,
    Flag NVARCHAR(10) NULL,
    FlagUrl NVARCHAR(500) NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    LastModifiedDate DATETIME2 NOT NULL DEFAULT GETDATE()
);